name: CI
on:
  push:
    branches-ignore:
      - 'gh-pages'
  pull_request:
    branches-ignore:
      - 'gh-pages'

jobs:
  jdk8:
    name: OpenJDK 8 (Windows)
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: TheMrMilchmann/install-jdk@v1
        with:
          version: '1.8'
      - uses: TheMrMilchmann/install-jdk@v1
        with:
          version: '9'
          targets: 'JDK_9'
      - uses: TheMrMilchmann/install-jdk@v1
        with:
          version: '13'
          targets: 'JDK_13'
      - name: Gradle Build
        run: |
          ./gradlew --version --console=plain
          ./gradlew build -Psnapshot --info -S --console=plain
          ./gradlew publish -Psnapshot --info -S --console=plain